# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b78698865c818a2f226a427188b748c608020b266c40efa0a35d84b5e552a4a507fa076c1779760df3a55d3e41f9f404675092a38b29414310215ec122b9c6e

test:
  secret_key_base: fbd91d16a1e0cf683afb56c70a09e001a973d5aeec77952c6e8fbb824da8fd64965d1e669580d3cd203dbc2d2d8e68db444dca2bdce7bf44e27d1ef46bec1a15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
